name: Build and Upload APK

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_upload_apk:
    name: Build and Upload APK
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Save APK artifact
        if: github.event.pull_request.head.ref == 'dev'
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: build\app\outputs\flutter-apk\app-debug.apk

      - name: Release APK
        if: github.event.pull_request.head.ref == 'main'
        run: flutter build apk --release

      - name: Save Release APK artifact
        if: github.event.pull_request.head.ref == 'main'
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build\app\outputs\flutter-apk\app-release.apk

      # - name: Upload APK to Google Drive
      #   if: github.event.pull_request.head.ref == 'dev' || github.event.pull_request.head.ref == 'main'
      #   uses: jakejarvis/google-drive-upload-action@v2.2.1
      #   with:
      #     serviceAccountJson: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
      #     filePath: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-debug.apk
      #     folderId: 1lPqOuh_QbS1vhw7aa7fX4I6SOAmYNzKz # Replace this with the ID of your Google Drive folder
